spring.application.name=datn

# ==========================================
# SQL Server Database
# ==========================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GymProDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=kudoha
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Server
# ==========================================
server.port=8080
